const node = (id, type, title, x, y, data = {}) => ({id, type, title, position: {x, y: Math.round(y * 0.76)}, data});
const edge = (source, target, branch = null) => ({id: `${source}-${branch || 'next'}-${target}`, source, target, branch});
const graph = (title, nodes, edges) => ({version: 1, title, nodes, edges, viewport: {x: 0, y: 0, zoom: 1}});
const start = () => node('start', 'start', '開始', 320, 60);
const end = (y = 700) => node('end', 'end', '結束', 320, y);
const input = (id, variable, prompt, x, y, inputType = 'number') => node(id, 'input', prompt, x, y, {variable, prompt, inputType});
const process = (id, title, expression, x, y) => node(id, 'process', title, x, y, {expression});
const output = (id, title, expression, x, y) => node(id, 'output', title, x, y, {expression});
const decision = (id, title, expression, x, y) => node(id, 'decision', title, x, y, {expression});

export const EXAMPLES = [
  {id: 'greeting', title: '你好，流程圖', description: '讀取姓名，再輸出問候語。認識輸入、文字與輸出。', input: '小明', graph: graph('你好，流程圖', [start(), input('name', 'name', '你叫什麼名字？', 320, 190, 'text'), output('hello', '輸出問候語', 'name + "，你好！"', 320, 320), end(450)], [edge('start', 'name'), edge('name', 'hello'), edge('hello', 'end')])},
  {id: 'parity', title: '奇數還是偶數？', description: '用餘數運算與條件分支判斷奇偶數。試試 8 與 7。', input: '8', graph: graph('奇數還是偶數？', [start(), input('number', 'number', '請輸入整數', 320, 190, 'integer'), decision('even', '可以被 2 整除嗎？', 'number % 2 == 0', 320, 320), output('yes', '偶數', '"偶數"', 130, 480), output('no', '奇數', '"奇數"', 510, 480), end(640)], [edge('start', 'number'), edge('number', 'even'), edge('even', 'yes', 'true'), edge('even', 'no', 'false'), edge('yes', 'end'), edge('no', 'end')])},
  {id: 'pass', title: '成績及格判斷', description: '輸入成績，觀察 >= 60 如何決定分支。', input: '85', graph: graph('成績及格判斷', [start(), input('score', 'score', '請輸入成績', 320, 190), decision('passed', '是否及格？', 'score >= 60', 320, 320), output('yes', '及格', '"及格"', 130, 480), output('no', '繼續加油', '"繼續加油"', 510, 480), end(640)], [edge('start', 'score'), edge('score', 'passed'), edge('passed', 'yes', 'true'), edge('passed', 'no', 'false'), edge('yes', 'end'), edge('no', 'end')])},
  {id: 'max', title: '找出較大的數', description: '輸入兩個數字，比較後輸出較大值；每行輸入一個值。', input: '12\n7', graph: graph('找出較大的數', [start(), input('a', 'a', '第一個數字', 320, 190), input('b', 'b', '第二個數字', 320, 320), decision('compare', '第一個數字較大嗎？', 'a >= b', 320, 450), output('yes', '輸出第一個數字', 'a', 130, 610), output('no', '輸出第二個數字', 'b', 510, 610), end(770)], [edge('start', 'a'), edge('a', 'b'), edge('b', 'compare'), edge('compare', 'yes', 'true'), edge('compare', 'no', 'false'), edge('yes', 'end'), edge('no', 'end')])},
  {id: 'sum', title: '1 到 n 的總和', description: '跟著迴圈觀察 i 與 total，每次逐步累加直到 n。', input: '5', graph: graph('1 到 n 的總和', [start(), input('n', 'n', '請輸入非負整數 n', 320, 190, 'integer'), process('total', '總和歸零', 'total = 0', 320, 320), process('index', '從 1 開始', 'i = 1', 320, 450), decision('loop', '還沒超過 n？', 'i <= n', 320, 580), process('add', '累加目前數字', 'total = total + i', 100, 750), process('increment', '前往下一個數字', 'i = i + 1', 100, 890), output('answer', '輸出總和', 'total', 570, 750), node('end', 'end', '結束', 570, 890)], [edge('start', 'n'), edge('n', 'total'), edge('total', 'index'), edge('index', 'loop'), edge('loop', 'add', 'true'), edge('add', 'increment'), edge('increment', 'loop'), edge('loop', 'answer', 'false'), edge('answer', 'end')])},
  {id: 'count', title: '從 1 數到 10', description: '用迴圈輸出 1 到 10，再倒回觀察 i 如何變化。', input: '', graph: graph('從 1 數到 10', [start(), process('index', '從 1 開始', 'i = 1', 320, 190), decision('loop', '還沒超過 10？', 'i <= 10', 320, 320), output('number', '輸出目前數字', 'i', 120, 480), process('increment', '加 1', 'i = i + 1', 120, 620), node('end', 'end', '結束', 560, 480)], [edge('start', 'index'), edge('index', 'loop'), edge('loop', 'number', 'true'), edge('number', 'increment'), edge('increment', 'loop'), edge('loop', 'end', 'false')])},
  {id: 'infinite', title: '無限迴圈實驗', description: '條件永遠為 True。觀察迴圈如何重複，以及系統如何安全中止。', input: '', graph: graph('無限迴圈實驗', [start(), process('index', '從 0 開始', 'i = 0', 320, 190), decision('loop', '永遠成立', 'True', 320, 320), process('increment', '持續加 1', 'i = i + 1', 110, 490), node('end', 'end', '結束', 560, 490)], [edge('start', 'index'), edge('index', 'loop'), edge('loop', 'increment', 'true'), edge('increment', 'loop'), edge('loop', 'end', 'false')])},
];
